### ISSUE TITLE
esp_attr.h Missing

### ISSUE THREAD

**Issue by ats3788** [hallard/Makerfabs-LvglWidgetsDemo#2]
from src/lv_demo_widgets/img_lvgl_logo.c:1:
d:\.pioenvs\libdeps\makerfab-70\lvgl\src\lv_conf_kconfig.h:16:14: fatal error: esp_attr.h: No such file or directory

******************************************************************
* Looking for esp_attr.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_attr.h"
* Web  > https://registry.platformio.org/search?q=header:esp_attr.h

**Comment by hallard** [comment]
just cloned to check up, launched vscode, opened project wait vscode and platformio end of setup, all is building fine you should check vscode/platformio config
